"""Portable passphrase-encrypted bundle for credentials + Playwright profiles."""

from __future__ import annotations

import base64
import gzip
import json
import os
import shutil
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from hashlib import scrypt
from pathlib import Path
from typing import Any

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from auth.secrets import AUTH_DIR, SECRETS_FILE, load_doc, profile_dir, save_doc

ROOT = Path(__file__).resolve().parents[1]
PROFILES_ROOT = AUTH_DIR / "profiles"

MAGIC = b"BAKLOGSB"
BUNDLE_VERSION = 1
INNER_FORMAT = 1
SCRYPT_N_LOG = 14
SCRYPT_R = 8
SCRYPT_P = 1
MIN_PASSPHRASE_LEN = 8
MAX_BUNDLE_BYTES = 100 * 1024 * 1024

_SKIP_PROFILE_SUFFIXES = (
    ".lock",
    ".tmp",
    "-journal",
    "-wal",
    "-shm",
)
_SKIP_PROFILE_NAMES = frozenset(
    {
        "LOCK",
        "SingletonLock",
        "SingletonCookie",
        "SingletonSocket",
        "lockfile",
    }
)


class BundleError(Exception):
    """Base error for portable bundle operations."""


class BadPassphrase(BundleError):
    """Decryption failed — wrong passphrase or corrupted ciphertext."""


class BadMagic(BundleError):
    """File is not a BAKLOG secrets bundle."""


class UnsupportedVersion(BundleError):
    """Bundle version is newer than this build understands."""


class BundleTooLarge(BundleError):
    """Bundle exceeds the maximum allowed size."""


@dataclass
class ImportSummary:
    providers_imported: list[str] = field(default_factory=list)
    profiles_imported: list[str] = field(default_factory=list)
    bytes_written: int = 0
    dry_run: bool = False

    def as_dict(self) -> dict[str, Any]:
        return {
            "providers_imported": list(self.providers_imported),
            "profiles_imported": list(self.profiles_imported),
            "bytes_written": self.bytes_written,
            "dry_run": self.dry_run,
        }


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _app_version() -> str:
    try:
        import tomllib

        with (ROOT / "pyproject.toml").open("rb") as fh:
            return str(tomllib.load(fh)["project"]["version"])
    except Exception:
        return "unknown"


def _validate_passphrase(passphrase: str) -> None:
    if len((passphrase or "").strip()) < MIN_PASSPHRASE_LEN:
        raise ValueError(f"passphrase must be at least {MIN_PASSPHRASE_LEN} characters")


def _derive_key(passphrase: str, salt: bytes) -> bytes:
    return scrypt(
        passphrase.encode("utf-8"),
        salt=salt,
        n=2**SCRYPT_N_LOG,
        r=SCRYPT_R,
        p=SCRYPT_P,
        dklen=32,
    )


def _should_skip_profile_file(path: Path) -> bool:
    name = path.name
    if name in _SKIP_PROFILE_NAMES:
        return True
    if name.startswith("."):
        return True
    return any(name.endswith(suffix) for suffix in _SKIP_PROFILE_SUFFIXES)


def _collect_profiles() -> dict[str, dict[str, str]]:
    out: dict[str, dict[str, str]] = {}
    if not PROFILES_ROOT.is_dir():
        return out
    for provider_dir in sorted(PROFILES_ROOT.iterdir()):
        if not provider_dir.is_dir():
            continue
        files: dict[str, str] = {}
        for file_path in provider_dir.rglob("*"):
            if not file_path.is_file() or _should_skip_profile_file(file_path):
                continue
            rel = file_path.relative_to(provider_dir).as_posix()
            try:
                files[rel] = base64.b64encode(file_path.read_bytes()).decode("ascii")
            except OSError:
                continue
        if files:
            out[provider_dir.name] = files
    return out


def _build_inner_payload(*, include_profiles: bool) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "bundle_format": INNER_FORMAT,
        "exported_at": _now_iso(),
        "app_version": _app_version(),
        "secrets_doc": load_doc(),
        "profiles": _collect_profiles() if include_profiles else {},
        "note": "Generated by BAKLOG. Local-only. See PRIVACY.md.",
    }
    return payload


def _encrypt_payload(passphrase: str, inner: dict[str, Any]) -> bytes:
    salt = os.urandom(16)
    nonce = os.urandom(12)
    key = _derive_key(passphrase, salt)
    plaintext = gzip.compress(json.dumps(inner, ensure_ascii=False).encode("utf-8"), compresslevel=6)
    ciphertext = AESGCM(key).encrypt(nonce, plaintext, None)
    header = (
        MAGIC
        + bytes([BUNDLE_VERSION, SCRYPT_N_LOG, SCRYPT_R, SCRYPT_P])
        + salt
        + nonce
    )
    return header + ciphertext


def _decrypt_payload(blob: bytes, passphrase: str) -> dict[str, Any]:
    if len(blob) > MAX_BUNDLE_BYTES:
        raise BundleTooLarge(f"bundle exceeds {MAX_BUNDLE_BYTES} bytes")
    if len(blob) < len(MAGIC) + 4 + 16 + 12 + 16:
        raise BadMagic("bundle is too short")
    if blob[: len(MAGIC)] != MAGIC:
        raise BadMagic("invalid bundle magic")
    version = blob[len(MAGIC)]
    if version != BUNDLE_VERSION:
        raise UnsupportedVersion(f"unsupported bundle version {version}")
    offset = len(MAGIC) + 4
    salt = blob[offset : offset + 16]
    nonce = blob[offset + 16 : offset + 28]
    ciphertext = blob[offset + 28 :]
    key = _derive_key(passphrase, salt)
    try:
        plaintext = AESGCM(key).decrypt(nonce, ciphertext, None)
    except Exception as exc:
        raise BadPassphrase("could not decrypt bundle — wrong passphrase or corrupted file") from exc
    try:
        inner = json.loads(gzip.decompress(plaintext).decode("utf-8"))
    except Exception as exc:
        raise BadPassphrase("decrypted payload is not valid") from exc
    if not isinstance(inner, dict):
        raise BadPassphrase("decrypted payload is not an object")
    return inner


def export_bundle(passphrase: str, *, include_profiles: bool = True) -> bytes:
    """Build a passphrase-encrypted portable bundle."""
    _validate_passphrase(passphrase)
    inner = _build_inner_payload(include_profiles=include_profiles)
    blob = _encrypt_payload(passphrase, inner)
    if len(blob) > MAX_BUNDLE_BYTES:
        raise BundleTooLarge(f"bundle exceeds {MAX_BUNDLE_BYTES} bytes")
    return blob


def _atomic_write_bytes(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    try:
        tmp.write_bytes(data)
        os.replace(tmp, path)
    except Exception:
        try:
            if tmp.exists():
                tmp.unlink()
        except OSError:
            pass
        raise


def _snapshot_profiles_dir() -> Path | None:
    if not PROFILES_ROOT.exists() or not any(PROFILES_ROOT.iterdir()):
        return None
    stamp = time.strftime("%Y%m%d-%H%M%S", time.localtime())
    dest = AUTH_DIR / f"profiles_pre_import_{stamp}"
    shutil.move(str(PROFILES_ROOT), str(dest))
    return dest


def _restore_profiles(profiles: dict[str, Any], *, dry_run: bool) -> tuple[list[str], int]:
    imported: list[str] = []
    bytes_written = 0
    if not isinstance(profiles, dict):
        return imported, bytes_written
    for provider, files in profiles.items():
        if not isinstance(provider, str) or not isinstance(files, dict) or not files:
            continue
        imported.append(provider)
        if dry_run:
            for b64 in files.values():
                if isinstance(b64, str):
                    bytes_written += len(b64) * 3 // 4
            continue
        target = profile_dir(provider)
        if target.exists():
            shutil.rmtree(target, ignore_errors=True)
        target.mkdir(parents=True, exist_ok=True)
        for rel, b64 in files.items():
            if not isinstance(rel, str) or not isinstance(b64, str):
                continue
            out_path = target / rel
            out_path.parent.mkdir(parents=True, exist_ok=True)
            data = base64.b64decode(b64.encode("ascii"))
            _atomic_write_bytes(out_path, data)
            bytes_written += len(data)
    return imported, bytes_written


def import_bundle(blob: bytes, passphrase: str, *, dry_run: bool = False) -> ImportSummary:
    """Decrypt and apply a portable bundle."""
    _validate_passphrase(passphrase)
    inner = _decrypt_payload(blob, passphrase)
    if inner.get("bundle_format") != INNER_FORMAT:
        raise UnsupportedVersion("unsupported inner bundle format")

    secrets_doc = inner.get("secrets_doc")
    if not isinstance(secrets_doc, dict):
        raise BadPassphrase("bundle missing secrets_doc")

    providers = sorted(
        k for k, v in (secrets_doc.get("providers") or {}).items() if isinstance(v, dict) and v
    )
    summary = ImportSummary(providers_imported=providers, dry_run=dry_run)

    if dry_run:
        profiles = inner.get("profiles") or {}
        profile_names, profile_bytes = _restore_profiles(profiles, dry_run=True)
        summary.profiles_imported = profile_names
        summary.bytes_written = profile_bytes
        if isinstance(secrets_doc, dict):
            summary.bytes_written += len(json.dumps(secrets_doc).encode("utf-8"))
        return summary

    _snapshot_profiles_dir()
    save_doc(secrets_doc)
    summary.bytes_written += SECRETS_FILE.stat().st_size if SECRETS_FILE.exists() else 0

    profiles = inner.get("profiles") or {}
    profile_names, profile_bytes = _restore_profiles(profiles, dry_run=False)
    summary.profiles_imported = profile_names
    summary.bytes_written += profile_bytes
    return summary


def bundle_filename() -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    return f"baklog-secrets-{stamp}.bundle"


def parse_bundle_header(blob: bytes) -> dict[str, Any]:
    """Lightweight header parse for tests and diagnostics."""
    if len(blob) < len(MAGIC) + 4:
        raise BadMagic("bundle is too short")
    if blob[: len(MAGIC)] != MAGIC:
        raise BadMagic("invalid bundle magic")
    return {
        "magic": blob[: len(MAGIC)].decode("ascii"),
        "version": blob[len(MAGIC)],
        "scrypt_n_log": blob[len(MAGIC) + 1],
        "scrypt_r": blob[len(MAGIC) + 2],
        "scrypt_p": blob[len(MAGIC) + 3],
    }
